app/urls.py
from django.urls import path, include

from .views import (
    home_view,
    login_view,
    logout_view,
    auth0_callback,
    edit_profile_view,
    view_user_profile_view,
    list_articles_view,
    create_article_view,
    get_article_subcategories_view,
    list_articles_by_tag_view,
    detail_article_view,
    list_articles_by_search_view,
    list_my_articles_view,
    edit_article_view,
    list_my_drafted_articles_view,
    delete_comment_view,
)

urlpatterns = [
    # Auth0 authentication ------------------------------------------------
    path("callback/", auth0_callback, name="auth0_callback"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("social_auth/", include("social_django.urls")),
    path("tinymce/", include("tinymce.urls")),
    # Local apps ----------------------------------------------------------
    path("home/", home_view, name="home"),
    path("user/profile/", edit_profile_view, name="profile"),
    path("user/<str:user_id>/", view_user_profile_view, name="view_user"),
    # articles  -----------------------------------------------------------
    path("articles/", list_articles_view, name="article_list"),
    path("articles/create/", create_article_view, name="article_create"),
    path(
        "articles/subcategories/",
        get_article_subcategories_view,
        name="article_subcategories",
    ),
    path("articles/tags/<str:tag>", list_articles_by_tag_view, name="article_tags"),
    path("articles/<int:article_id>/", detail_article_view, name="article_detail"),
    path("articles/search/", list_articles_by_search_view, name="article_search"),
    path("articles/my/", list_my_articles_view, name="article_my"),
    path(
        "articles/my/drafts/", list_my_drafted_articles_view, name="article_my_drafts"
    ),
    path("articles/<int:article_id>/edit/", edit_article_view, name="article_edit"),
    # comments  -----------------------------------------------------------
    path(
        "comments/<int:comment_id>/<int:article_id>/delete/",
        delete_comment_view,
        name="comment_delete",
    ),
]

collabo_rate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("app.urls"))]

app/forms.py
from django import forms
from taggit.forms import TagWidget
from tinymce.widgets import TinyMCE

from .models import Auth0User, Article, Comment
from .utils import MAIN_CATEGORIES


class EditProfileForm(forms.ModelForm):
    """
    This class represents a form for editing a user profile.
    """

    date_of_birth = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), required=False
    )

    class Meta:
        model = Auth0User
        fields = [
            "bio",
            "avatar",
            "location",
            "first_name",
            "last_name",
            "additional_name",
            "date_of_birth",
            "website",
            "education",
            "industry",
        ]


class ArticleCreateForm(forms.ModelForm):
    """
    This class represents a form for creating an article.
    """

    description = forms.CharField(
        max_length=250,
        widget=forms.Textarea(attrs={"rows": 2}),
        required=True,
        help_text="A short description of the article. Max 250 characters.",
    )

    main_category = forms.CharField(
        max_length=50,
        widget=forms.Select(choices=MAIN_CATEGORIES),
        required=True,
    )
    body = forms.CharField(
        widget=TinyMCE(attrs={"required": False, "cols": 30, "rows": 10})
    )

    class Meta:
        model = Article
        fields = [
            "title",
            "description",
            "body",
            "main_category",
            "subcategory",
            "tags",
        ]
        widgets = {
            "tags": TagWidget(),
        }


class ArticleEditForm(forms.ModelForm):
    """
    This class represents a form for editing an article.
    """

    description = forms.CharField(
        max_length=250,
        widget=forms.Textarea(attrs={"rows": 2}),
        required=True,
        help_text="A short description of the article. Max 250 characters.",
    )

    main_category = forms.CharField(
        max_length=50,
        widget=forms.Select(choices=MAIN_CATEGORIES),
        required=True,
    )
    body = forms.CharField(
        widget=TinyMCE(attrs={"required": False, "cols": 30, "rows": 10})
    )

    class Meta:
        model = Article
        fields = [
            "title",
            "description",
            "body",
            "main_category",
            "subcategory",
            "tags",
        ]
        widgets = {
            "tags": TagWidget(),
        }


class CommentCreateForm(forms.ModelForm):
    """
    This class represents a form for creating a comment.
    """
    content = forms.CharField(
        widget=TinyMCE(
            attrs={"required": False, "cols": 30, "rows": 10},
        )
    )

    class Meta:
        model = Comment
        fields = ["content"]

templates/app/comments/comment_widget.html
{% load widget_tweaks %}
{% load humanize %}
{% load static %}
<section>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        <div class="mt-3">
            <div class="justify-content-center">
                <div class="card">
                    <div class="card-body">
                        {% for comment in comments %}
                            <div class="d-flex flex-start align-items-center">
                                <img src="{{ comment.author.avatar.url }}"
                                     class="rounded-circle shadow-1-strong me-3" width="60" height="60">

                                <div>
                                    <h6 class="fw-bold text-primary">
                                        <a href="{% url "view_user" comment.author.id %}"
                                           class="text-decoration-none">@{{ comment.author }}</a>
                                    </h6>
                                    <p class="text-muted small mb-0">
                                        {% if comment.created_at|naturaltime == comment.updated_at|naturaltime %}
                                            {{ comment.created_at|naturaltime }}
                                        {% else %}
                                            {{ comment.updated_at|naturaltime }} (edited)
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                            <p class="mb-4 pb-2">
                                {{ comment.content|safe }}
                            </p>
                            <div class="small d-flex justify-content-start">
                                {% if comment.author.id == user.id %}
                                    <a href="{% url "comment_delete" comment.id article.id %}"
                                       class="d-flex align-items-center me-3 text-decoration-none">
                                        <p class="mb-0">Delete</p>
                                    </a>
                                {% endif %}
                            </div>
                            <hr>
                        {% endfor %}
                    </div>
                    {% if user.is_authenticated %}
                        <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
                            <div class="d-flex flex-start w-100">
                                <img class="rounded-circle shadow-1-strong me-3" src="{{ user.avatar.url }}"
                                     alt="avatar"
                                     width="40" height="40"/>
                                <div class="form-outline w-100">
                                    <label for="id_content">Comment</label>
                                    {{ form.content|add_class:"form-control" }}
                                    <div class="invalid-feedback">
                                        {{ form.content.errors }}
                                    </div>
                                </div>
                            </div>
                            <div class="float-end mt-2 pt-1">
                                <button type="submit" class="btn btn-info btn-sm">Post comment</button>
                            </div>
                        </div>
                    {% else %}
                        <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
                            <p>
                                <a href="{% url "login" %}?next={{ request.path }}" class="text-decoration-none">
                                    Log in
                                </a>
                                to make a comment.
                            </p>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </form>
</section>