app/urls.py
from django.urls import path, include

from .views import (
    home_view,
    login_view,
    logout_view,
    auth0_callback,
    edit_profile_view,
    view_user_profile_view,
    list_articles_view,
    create_article_view,
    get_article_subcategories_view,
    list_articles_by_tag_view,
    detail_article_view,
    list_articles_by_search_view,
    list_my_articles_view,
    edit_article_view,
    list_my_drafted_articles_view,
    delete_comment_view,
)

urlpatterns = [
    # Auth0 authentication ------------------------------------------------
    path("callback/", auth0_callback, name="auth0_callback"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("social_auth/", include("social_django.urls")),
    path("tinymce/", include("tinymce.urls")),
    # Local apps ----------------------------------------------------------
    path("home/", home_view, name="home"),
    path("user/profile/", edit_profile_view, name="profile"),
    path("user/<str:user_id>/", view_user_profile_view, name="view_user"),
    # articles  -----------------------------------------------------------
    path("articles/", list_articles_view, name="article_list"),
    path("articles/create/", create_article_view, name="article_create"),
    path(
        "articles/subcategories/",
        get_article_subcategories_view,
        name="article_subcategories",
    ),
    path("articles/tags/<str:tag>", list_articles_by_tag_view, name="article_tags"),
    path("articles/<int:article_id>/", detail_article_view, name="article_detail"),
    path("articles/search/", list_articles_by_search_view, name="article_search"),
    path("articles/my/", list_my_articles_view, name="article_my"),
    path(
        "articles/my/drafts/", list_my_drafted_articles_view, name="article_my_drafts"
    ),
    path("articles/<int:article_id>/edit/", edit_article_view, name="article_edit"),
    # comments  -----------------------------------------------------------
    path(
        "comments/<int:comment_id>/<int:article_id>/delete/",
        delete_comment_view,
        name="comment_delete",
    ),
]

collabo_rate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("app.urls"))]

app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from taggit.managers import TaggableManager
from tinymce.models import HTMLField

from .utils import MAIN_CATEGORIES


class Auth0User(AbstractUser):
    """
    This class extends the default Django user model with an Auth0 ID field.
    """

    auth0_id = models.CharField(max_length=255)
    bio = models.TextField(blank=True, null=True)
    avatar = models.ImageField(
        upload_to="static/avatars/",
        blank=True,
        null=True,
        default="static/avatars/default.png",
    )
    location = models.CharField(max_length=255, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)

    # Custom fields similar to LinkedIn
    website = models.CharField(max_length=255, blank=True, null=True)
    additional_name = models.CharField(max_length=255, blank=True, null=True)
    education = models.CharField(max_length=255, blank=True, null=True)
    industry = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.username


class Article(models.Model):
    """
    This class represents an article.
    """

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    author = models.ForeignKey(Auth0User, on_delete=models.CASCADE)
    body = HTMLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    main_category = models.CharField(
        max_length=50, choices=MAIN_CATEGORIES, default="Uncategorized"
    )
    subcategory = models.CharField(max_length=50, default="Uncategorized")
    tags = TaggableManager()
    published = models.BooleanField(default=False)
    comments = models.ManyToManyField(
        Auth0User, through="Comment", related_name="comments"
    )


class Comment(models.Model):
    """
    This class represents a comment.
    """

    content = HTMLField(blank=True, null=True)
    author = models.ForeignKey(Auth0User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

app/forms.py
from django import forms
from taggit.forms import TagWidget
from tinymce.widgets import TinyMCE

from .models import Auth0User, Article, Comment
from .utils import MAIN_CATEGORIES


class EditProfileForm(forms.ModelForm):
    """
    This class represents a form for editing a user profile.
    """

    date_of_birth = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), required=False
    )

    class Meta:
        model = Auth0User
        fields = [
            "bio",
            "avatar",
            "location",
            "first_name",
            "last_name",
            "additional_name",
            "date_of_birth",
            "website",
            "education",
            "industry",
        ]


class ArticleCreateForm(forms.ModelForm):
    """
    This class represents a form for creating an article.
    """

    description = forms.CharField(
        max_length=250,
        widget=forms.Textarea(attrs={"rows": 2}),
        required=True,
        help_text="A short description of the article. Max 250 characters.",
    )

    main_category = forms.CharField(
        max_length=50,
        widget=forms.Select(choices=MAIN_CATEGORIES),
        required=True,
    )
    body = forms.CharField(
        widget=TinyMCE(attrs={"required": False, "cols": 30, "rows": 10})
    )

    class Meta:
        model = Article
        fields = [
            "title",
            "description",
            "body",
            "main_category",
            "subcategory",
            "tags",
        ]
        widgets = {
            "tags": TagWidget(),
        }


class ArticleEditForm(forms.ModelForm):
    """
    This class represents a form for editing an article.
    """

    description = forms.CharField(
        max_length=250,
        widget=forms.Textarea(attrs={"rows": 2}),
        required=True,
        help_text="A short description of the article. Max 250 characters.",
    )

    main_category = forms.CharField(
        max_length=50,
        widget=forms.Select(choices=MAIN_CATEGORIES),
        required=True,
    )
    body = forms.CharField(
        widget=TinyMCE(attrs={"required": False, "cols": 30, "rows": 10})
    )

    class Meta:
        model = Article
        fields = [
            "title",
            "description",
            "body",
            "main_category",
            "subcategory",
            "tags",
        ]
        widgets = {
            "tags": TagWidget(),
        }


class CommentCreateForm(forms.ModelForm):
    """
    This class represents a form for creating a comment.
    """
    content = forms.CharField(
        widget=TinyMCE(
            attrs={"required": False, "cols": 30, "rows": 10},
        )
    )

    class Meta:
        model = Comment
        fields = ["content"]

templates/app/articles/article_create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load humanize %}
{% load static %}
{% block content %}
    <h2>Create Article</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        <div class="mb-3">
            <label for="{{ form.title.id_for_label }}" class="form-label">{{ form.title.label }}</label>
            {{ form.title|add_class:"form-control" }}
            {% if form.title.help_text %}
                <small class="form-text text-muted">{{ form.title.help_text }}</small>
            {% endif %}
            {% for error in form.title.errors %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="{{ form.description.id_for_label }}" class="form-label">{{ form.description.label }}</label>
            {{ form.description|add_class:"form-control" }}
            {% if form.description.help_text %}
                <small class="form-text text-muted">{{ form.description.help_text }}</small>
            {% endif %}
            {% for error in form.description.errors %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            {{ form.body|add_class:"form-control" }}
            {% if form.body.help_text %}
                <small class="form-text text-muted">{{ form.body.help_text }}</small>
            {% endif %}
            {% for error in form.body.errors %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="row mb-3">
            <div class="col">
                <label for="{{ form.main_category.id_for_label }}"
                       class="form-label">{{ form.main_category.label }}</label>
                {{ form.main_category|add_class:"form-control" }}
                {% if form.main_category.help_text %}
                    <small class="form-text text-muted">{{ form.main_category.help_text }}</small>
                {% endif %}
                {% for error in form.main_category.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="col">
                <label for="{{ form.subcategory.id_for_label }}"
                       class="form-label">{{ form.subcategory.label }}</label>
                <select name="{{ form.subcategory.html_name }}" class="form-control"
                        id="{{ form.subcategory.id_for_label }}">
                    <option selected>Select a subcategory</option>
                </select>
                {% if form.subcategory.help_text %}
                    <small class="form-text text-muted">{{ form.subcategory.help_text }}</small>
                {% endif %}
                {% for error in form.subcategory.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            </div>
        </div>
        <div class="mb-3">
            <label for="{{ form.tags.id_for_label }}" class="form-label">{{ form.tags.label }}</label>
            {{ form.tags|add_class:"form-control" }}
            {% if form.tags.help_text %}
                <small class="form-text text-muted">{{ form.tags.help_text }}</small>
            {% endif %}
            {% for error in form.tags.errors %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <input type="submit" class="btn btn-primary" name="set_published" value="Publish">
            <input type="submit" class="btn btn-outline-dark" name="set_published" value="Draft">
        </div>
    </form>
    {# Here, I want users to have a filtered view of the subcategory based on their main category selection #}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $('#id_main_category').change(function () {
                var selectedOption = $(this).val();
                $.ajax({
                    url: '/articles/subcategories/',  // URL of your Django view that returns the options
                    data: {
                        'option': selectedOption
                    },
                    success: function (data) {
                        $('#id_subcategory').html(data);
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/app/articles/article_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load widget_tweaks %}
{% block content %}
    <div class="card mt-3">
        <div class="card-header">
            <h5 class="card-title">{{ article.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ article.description }}</h6>
            <p class="card-text text-muted">
                Created by
                <a href="{% url "view_user" article.author.id %}" class="text-decoration-none">@{{ article.author }}</a>
                {% if article.created_at|naturaltime == article.updated_at|naturaltime %}
                    - {{ article.created_at|naturaltime }}
                {% else %}
                    - {{ article.updated_at|naturaltime }} (edited)
                {% endif %}
            </p>
        </div>
        <div class="card-body">
            <div class="article-body">
                {{ article.body|safe }}
            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex align-items-center">
                <div class="btn-group me-auto" role="group" aria-label="Basic outlined example">
                    Rating:&nbsp;
                    <button type="button" class="btn btn-outline-dark btn-sm">{{ article.calculate_rating }}</button>
                    <button type="button" class="btn btn-outline-dark btn-sm">👍</button>
                    <button type="button" class="btn btn-outline-dark btn-sm">👎</button>
                </div>
                {# If users own this article, give it an edit button #}
                {% if user.id == article.author.id %}
                    <a href="{% url "article_edit" article.id %}"
                       class="btn btn-sm btn-success ms-2">Edit</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% include "app/comments/comment_widget.html" %}
{% endblock %}

templates/app/articles/article_list.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
    <h1>{{ title }}</h1>
    {% include "app/search.html" %}
    <div class="accordion accordion-flush mt-3" id="accordionFlush">
        {% for category, articles in articles_by_category.items %}
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#flush-collapse{{ forloop.counter }}" aria-expanded="false"
                            aria-controls="flush-collapse{{ forloop.counter }}">
                        {{ category }}
                    </button>
                </h2>
            </div>
            <div id="flush-collapse{{ forloop.counter }}" class="accordion-collapse collapse"
                 data-bs-parent="#accordionFlush">
                <div class="accordion-body card">
                    {% for article in articles %}
                        <div class="card mt-3">
                            <div class="card-header">
                                <h5 class="card-title">{{ article.title }}</h5>
                                <h6 class="card-subtitle mb-2 text-body-secondary">{{ article.description }}</h6>
                                <p class="card-text text-muted">
                                    Author: <a href="{% url "view_user" article.author.id %}">@{{ article.author }}</a>
                                    | Rating: {{ article.calculate_rating }}
                                </p>
                            </div>
                            <div class="card-body">
                                <div class="tags">
                                    {% for tag in article.tags.all %}
                                        <a href="{% url "article_tags" tag.slug %}"
                                           class="badge bg-secondary">{{ tag }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="btn-group" role="group" aria-label="Basic outlined example">
                                    <a href="{% url "article_detail" article.id %}"
                                       class="btn btn-outline-primary btn-sm">View Article</a>
                                    <a href="{% url "article_detail" article.id %}#comments"
                                       class="btn btn-outline-info btn-sm">View Comments
                                        ({{ article.comments.count }})</a>
                                    {% if user.is_authenticated and user.id == article.author.id %}
                                        <a href="{% url "article_edit" article.id %}"
                                           class="btn btn-outline-success btn-sm">Edit Article</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/app/articles/article_widget.html
{% load humanize %}
{% for article in articles %}
    <div class="card mt-3">
        <div class="card-body">
            <div class="d-flex align-items-center mb-3">
                <img src="{{ article.author.avatar.url }}" alt="Profile Image" class="rounded-circle me-2" width="40">
                <div>
                    <a href="{% url "view_user" article.author.id %}" class="text-decoration-none text-dark fw-bold">
                        {% if article.author.id == user.id %}(You) {% endif %}@{{ article.author.username }}
                    </a>
                    <p class="text-muted mb-0">
                        {{ article.created_at|naturaltime }} •
                        <a href="{% url "article_detail" article.id %}#comments"
                           class="text-muted text-decoration-none">
                            Comments: {{ article.comments.count }}
                        </a>
                    </p>
                </div>
            </div>
            <figure>
                <blockquote class="blockquote">
                    <p>
                        <a class="text-decoration-none text-dark fw-bold"
                           href="{% url "article_detail" article.id %}">{{ article.title }}</a>
                        - <small>{{ article.description|truncatewords:25 }}</small>
                    </p>
                </blockquote>
                <figcaption class="blockquote-footer">
                    by <cite title="Source Title">@{{ article.author.username }}</cite>
                </figcaption>
            </figure>
            <div class="mt-3">
                {# If users own this article, give it an edit button #}
                {% if user.id == article.author.id %}
                    <a class="btn btn-sm btn-info me-2">{% if article.published %}Published{% else %}
                        Drafted{% endif %}</a>
                    <a href="{% url "article_edit" article.id %}"
                       class="btn btn-sm btn-success me-2">Edit</a>
                {% endif %}
                {% for tag in article.tags.all %}
                    <a href="{% url "article_tags" tag.slug %}"
                       class="btn btn-sm btn-secondary me-2">{{ tag }}</a>
                {% endfor %}
                <span class="badge bg-primary">{{ article.calculate_rating }}</span>
            </div>
        </div>
    </div>
{% endfor %}

templates/app/articles/articles_searched.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
    <h3>Searching for Articles containing the phrase <i>{{ query }}</i></h3>
    <hr>
    {% include "app/articles/article_widget.html" %}
{% endblock %}

templates/app/articles/articles_tagged.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ title }}<b>: {{ tag }}</b></h1>
    <hr>
    {% include "app/articles/article_widget.html" %}
{% endblock %}